-- MySQL Script generated by MySQL Workbench
-- Wed Oct 17 20:14:33 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(45) NULL,
  `sobrenomeCliente` VARCHAR(45) NULL,
  `senhaCliente` VARCHAR(45) NULL,
  `pessoajuridicaCliente` TINYINT NULL DEFAULT 0,
  `cpfCliente` INT NULL,
  `cnpjCliente` VARCHAR(45) NULL,
  `fotoCliente` VARCHAR(150) NULL,
  `dataCriacaoCliente` DATE NULL,
  `dataAlteracaoCliente` DATE NULL,
  `Clientecol` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `cepEndereco` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NULL,
  `Cidade_idCidade` INT NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `idCidade` INT NOT NULL AUTO_INCREMENT,
  `Estado_idEstado` INT NULL,
  `nomeCidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idCidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nomeEstado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carrinho` (
  `idCarrinho` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Carrinho_idCarrinho` INT NOT NULL,
  PRIMARY KEY (`idCarrinho`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `destaqueProduto` TINYINT NULL DEFAULT 0,
  `nomeProduto` VARCHAR(45) NULL,
  `estoqueProduto` INT NULL,
  `skuProduto` VARCHAR(45) NULL,
  `valorProduto` FLOAT NULL,
  `valorDescontoProduto` FLOAT NULL,
  `descricaoProduto` VARCHAR(500) NULL,
  `fotoProduto` VARCHAR(45) NULL,
  `dataCriacaoProduto` DATE NULL,
  `dataAlteracaoProduto` DATE NULL,
  `Produtocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Propriedades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Propriedades` (
  `Produto_idProduto` INT NOT NULL,
  `chavePropriedade` VARCHAR(45) NULL,
  `valorPropriedade` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nomeCategoria` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProdutoCategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProdutoCategoria` (
  `Produto_idProduto` INT NOT NULL,
  `Categoria_idCategoria` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento` (
  `idPagamento` INT NOT NULL AUTO_INCREMENT,
  `tipoPagamento` VARCHAR(45) NULL,
  PRIMARY KEY (`idPagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entrega` (
  `idEntrega` INT NOT NULL AUTO_INCREMENT,
  `nomeEntrega` VARCHAR(45) NULL,
  `dataEntrega` DATE NULL,
  `Entregacol` VARCHAR(45) NULL,
  PRIMARY KEY (`idEntrega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StatusPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StatusPedido` (
  `idStatusPedido` INT NOT NULL AUTO_INCREMENT,
  `nomeStatus` VARCHAR(45) NULL,
  PRIMARY KEY (`idStatusPedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dataPedido` DATE NULL,
  `valorPedido` FLOAT NULL,
  `Pedidocol` VARCHAR(45) NULL,
  `Pagamento_idPagamento` INT NOT NULL,
  `StatusPedido_idStatusPedido` INT NOT NULL,
  `Entrega_idEntrega` INT NOT NULL,
  PRIMARY KEY (`idPedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Item` (
  `Pedido_idPedido` INT UNSIGNED NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `Carrinho_idCarrinho` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Foto` (
  `idFoto` INT NOT NULL AUTO_INCREMENT,
  `localFoto` VARCHAR(45) NULL,
  `Produto_idProduto` INT NOT NULL,
  PRIMARY KEY (`idFoto`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- cadastros

INSERT INTO `mydb`.`cliente`
(`nomeCliente`,
`sobrenomeCliente`,
`senhaCliente`,
`pessoajuridicaCliente`,
`cpfCliente`,
`cnpjCliente`,
`fotoCliente`,
`dataCriacaoCliente`,
`dataAlteracaoCliente`,
`Clientecol`)
VALUES
('Dinara'>,
<'Pereira Lima'>,
<'nem vale'>,
<0>,
<'0000009'>,
<>,
<'nem vale'>,
<'nem vale'>,
<'nem vale'>,
<{Clientecol: }>);



